version: "3"

services:
  redis:
    build:
      context: redis
      dockerfile: ./Dockerfile
    ports:
      - 6379:6379

  data-emitter:
    build:
      context: DataEmitter
      dockerfile: ./Dockerfile
    depends_on: 
      - kafka
    volumes:
      - type: bind
        source: ./DataEmitter/data/logs.txt
        target: /data/logs.txt
        read_only: true
    command: sh -c "sleep 5 && python ./main.py 1"

  storm:
    build:
      context: storm
      dockerfile: ./Dockerfile
    depends_on:
      - redis
      - zookeeper
      - kafka
    command: sh -c "sleep 10 && mvn exec:java -Dexec.classpathScope=compile -Dexec.mainClass=Program"

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    hostname: zookeeper
    expose:
      - "2181"

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - 9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
