version: "3"

services:
  dashboard-frontend:
    build:
      context: dashboard-frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  dashboard-backend:
    hostname: dashboard-backend
    build:
      context: dashboard-backend
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
  redis:
    build:
      context: redis
      dockerfile: ./Dockerfile
    ports:
      - 6379:6379

  data-emitter:
    build:
      context: DataEmitter
      dockerfile: ./Dockerfile
    depends_on:
      - kafka
    volumes:
      - type: bind
        source: ./DataEmitter/data
        target: /data/
        read_only: false
      - type: bind
        source: ${TAXI_DATASET}
        target: /dataset/
        read_only: true
    command: sh -c "sleep 5 && python -u ./main.py --dataset /dataset/ --sorted_logs /data/logs.txt --speed_multiplier 2 --max_taxis 100"

  storm:
    build:
      context: storm
      dockerfile: ./Dockerfile
    depends_on:
      - redis
      - zookeeper
      - kafka
    command: sh -c "sleep 10 && mvn exec:java -Dexec.classpathScope=compile -Dexec.mainClass=Program"

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    hostname: zookeeper
    expose:
      - "2181"

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - 9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
